#!/usr/bin/env ruby
# -- @robzr

#GHREP#
require_relative 'lib/ghrep.rb'

require 'pp'

begin
  options = Ghrep::ParseCommandLineArgs.instance().parse(ARGV)
  repos = Ghrep::Repos.new(options)
  eval "repos.#{options[:command].to_s}!"
rescue Ghrep::GitHubError => error
  print "GitHubError Exception: #{error.message} "
  if (options[:log_level] > 1)
    puts error.backtrace.join("\n -> ")
  else
    puts error.backtrace[0..1].join("\n -> ")
  end
  exit(-1)
rescue Ghrep::ParseTermsError => error
  puts error.message
  exit(-1)
rescue Ghrep::RepoSpecError
  exit(-1)
rescue OptionParser::InvalidOption => error
  puts error.message
  puts parser
  exit(-1)
end
