#!/usr/bin/env ruby
# -- @robzr

require 'pp'
require_relative 'lib/ghrep.rb'

begin
  options = Ghrep::ParseCommandLineArgs.instance().parse(ARGV)
  repos = Ghrep::Repos.new(options)
  eval "repos.#{options[:command].to_s}!"
rescue Ghrep::GitHubError => error
  if error.message.to_s == '404'
    puts "Github user or org not found.  Use -h for help.  Hint: try setting GITHUB_ORG and/or GITHUB_USER"
  else
    print "GitHubError Exception: #{error.message} "
    puts error.backtrace.take(options[:log_level] < 2 ? 2 : 100).join("\n -> ")
  end
  exit(-1)
rescue Ghrep::ParseTermsError => error
  puts error.message
  exit(-1)
rescue Ghrep::RepoSpecError
  exit(-1)
rescue OptionParser::InvalidOption => error
  puts error.message
  puts parser
  exit(-1)
end
